### PR TITLE
#Issue 6 solution

### PR DESCRIPTION
**Pull request by quantumgizmos**

### CODE REVIEW

**Comment by peter-janderks** [comment]
I'll merge this :smile: I've rewritten everything in the QEC class that uses this protograph class

 A couple of small thoughts:

1. I don't know why you added tests under if __name__ == '__main__'

2. The code is now more than 2x as slow as the previous version of the protograph class, tested with:

```
import timeit

n_runs = 100000

setup_code = '''
from protograph import Protograph
import numpy as np
a = Protograph(10,np.array([[{0,2} for _ in range(10)]])) 
b = np.eye(1) 
'''
print(timeit.timeit(setup=setup_code, stmt='Protograph.kron(a,b)', number=n_runs))

setup_code = '''
from ldpc.protograph import array
import numpy as np 
a = array([[[0,2] for _ in range(10) ]])
b = array([[[0]]])
'''
print(timeit.timeit(setup=setup_code, stmt='np.kron(a,b)',  number=n_runs))
```

3. I think the code of the previous class was considerably more clear:

```
class Protograph(object):
    '''Class for representating Protographs with operations used for constructing
    lifted hypergraph product codes.
    Attributes:
        lift_parameter (int): The size of the square permutation matrices that
                              form the protograph
        shape (tuple): number of rows and columns
        polynomial matrix (np.array): Matrix whose elements are sets. The sets
                                      contain integers 'x' which each
                                      represent permutation matrices with
                                      shift parameter 'x'.
    Example:
        The 3x3 repetition code can be represented using creating the
        following class instance: Protograph(3,np.array([[{0,2}]]))
    '''

    def __init__(self, lift_parameter, polynomial_matrix):
        ''' Creates a Protograph object.
        Args:
            lift_parameter (int): The size of the square permutation matrices
                                  that form the protograph
            polynomial_matrix (np.array): Matrix whose elements are sets. The
                                          sets contain integers 'x' which each
                                          represent permutation matrices with
                                          shift parameter 'x'.
        Note that the entries of the polynomial matrix must be lower
        than the lift parameter
        '''
        self.lift_parameter = lift_parameter
        self.polynomial_matrix = polynomial_matrix
        self.shape = polynomial_matrix.shape
```

**Comment by quantumgizmos** [comment]
Thanks.

1. The main __name__ == '__main__' is just a scratch space for quick testing. It was what runs when you run the test file directly. It can be deleted.
2. I wonder where the speed difference is coming from? It seems odd that the native numpy implementation would be slower than the hard-coded one? In any case, this is not the bottle neck at this stage. The real thing that is slowing down code construction is the fact we are using the python implementation of Gaussian elimination to compute the logical operators. We should look at re-implementing this in Cython. 
3. Lets discuss class naming etc. My intention was to make this package mirror numpy as closely as possible. ie. I want to be able to change a function from binary to the ring algebra simply by swapping out `np` for `pt` where `pt` is imported as

```
import ldpc.protograph as pt
```

**Comment by peter-janderks** [comment]
Ok I see. I thought the entire point of replacing my code from scratch was to speed it up. Also in my code, np could be switched out by pt, I had implemented pt.kron, pt.hstack, pt.vstack etc.

**Comment by quantumgizmos** [comment]
How do the two methods compare for larger protographs? Can you run the kron test on two 30x30 protographs (that aren't the identity protograph)?

**Comment by peter-janderks** [comment]
my class: 2.96641714100042 seconds 
your class: 56.970642016000056 seconds

Like I said, the problem is your init function.

**Comment by peter-janderks** [comment]
But I think we don't need to discuss more, I have made the changes in the QEC repository to change to this new version and everything is working.

**Pull request merged**
